#!/usr/bin/env python3
"""Generate a machine-readable build provenance record for a release artifact.

This script replaces hand-authored provenance sidecars (e.g. a manually edited
``jdbc-artifact.manifest``) with a JSON record derived from the artifact bytes
that CI *actually produced*, plus the git commit that is checked out when the
script runs. It never accepts a pre-existing hash or commit value as input:
those facts are always recomputed here so the record cannot silently drift
from reality.

By default the script only accepts protected release tags in the form
``vMAJOR.MINOR.PATCH`` (e.g. ``v4.3.4``) as the build ``--ref``, and requires
that the version segment of ``--gav`` match that tag exactly. Both checks may
be bypassed with ``--allow-non-release-ref``, which exists ONLY for local
testing / POC builds and must never be used for a production publication
path. When used, the resulting record is annotated implicitly by the caller's
own process (this script does not mark the file as "non-release" internally
beyond emitting a warning), so downstream consumers that require a protected
release must re-derive that guarantee themselves rather than trusting this
flag was unset.

Output schema (schemaVersion 1)::

    {
      "schemaVersion": 1,
      "artifactType": "jar",
      "gav": "net.snowflake:snowflake-jdbc:4.3.4",
      "sha256": "<64 lowercase hex characters>",
      "source": {
        "repository": "snowflakedb/snowflake-jdbc",
        "commit": "<40 hex character git commit sha>",
        "ref": "v4.3.4"
      },
      "build": {
        "id": "<CI build id>"
      }
    }

Example (CI invocation)::

    python3 scripts/generate-build-provenance.py \\
      --artifact-path ~/.ivy2/local/com.snowflake/snowpark_2.12/1.22.0/jars/snowpark_2.12.jar \\
      --gav com.snowflake:snowpark_2.12:1.22.0 \\
      --ref v1.22.0 \\
      --build-id "$BUILD_ID" \\
      --output build/provenance/snowpark_2.12.provenance.json

This record is later combined with the JDBC and adapter build provenance
records (each generated by this same script in their own repositories) into
a signed compatibility set once cross-repository compatibility tests pass.
The signed set and its adapter JAR/sha256/manifest are published exclusively
by ``Python/anaconda_mirror/publish_jdbc_compatibility_set.sh`` in the
``snowflake`` repo -- this repo's release pipeline (``scripts/deploy-common.sh``)
does not consume or re-publish the compatibility set itself; it only
produces this Snowpark build provenance record as one of the three inputs.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from typing import NamedTuple, Optional, Sequence

# Only immutable, protected release tags are accepted by default. Branches,
# raw commit hashes, "HEAD", and option-like strings are all rejected.
RELEASE_REF_PATTERN = re.compile(r"^v[0-9]+\.[0-9]+\.[0-9]+$")

# A git commit sha (SHA-1 object format, which is what `git rev-parse HEAD`
# returns in all repositories this script currently targets).
GIT_COMMIT_PATTERN = re.compile(r"^[0-9a-f]{40}$")

SHA256_HEX_PATTERN = re.compile(r"^[0-9a-f]{64}$")

DEFAULT_REPOSITORY = "snowflakedb/snowpark-java-scala"
DEFAULT_ARTIFACT_TYPE = "jar"

SCHEMA_VERSION = 1


class ProvenanceError(ValueError):
    """Raised when an input fails validation and provenance cannot be trusted."""


class Gav(NamedTuple):
    group_id: str
    artifact_id: str
    version: str


def split_gav(gav: str) -> Gav:
    """Validate that ``gav`` has exactly 3 non-empty colon-separated segments."""
    parts = gav.split(":")
    if len(parts) != 3 or not all(part.strip() for part in parts):
        raise ProvenanceError(
            "GAV must have exactly 3 non-empty colon-separated segments "
            f"(groupId:artifactId:version), got: {gav!r}"
        )
    return Gav(*parts)


def compute_sha256(artifact_path: str) -> str:
    """Compute the SHA-256 digest of the file at ``artifact_path``."""
    if not os.path.isfile(artifact_path):
        raise ProvenanceError(
            f"artifact path does not exist or is not a regular file: {artifact_path!r}"
        )
    digest = hashlib.sha256()
    with open(artifact_path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def resolve_git_commit(repo_root: str) -> str:
    """Return the full commit sha checked out at ``repo_root``."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repo_root,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except FileNotFoundError as exc:
        raise ProvenanceError(f"git executable not found: {exc}") from exc
    except subprocess.CalledProcessError as exc:
        stderr = (exc.stderr or "").strip()
        raise ProvenanceError(
            f"failed to resolve git commit in {repo_root!r}: {stderr or exc}"
        ) from exc

    commit = result.stdout.strip()
    if not GIT_COMMIT_PATTERN.match(commit):
        raise ProvenanceError(f"unexpected output from 'git rev-parse HEAD': {commit!r}")
    return commit


def validate_ref(ref: str, gav_version: str, allow_non_release_ref: bool) -> None:
    """Reject non-release refs and version/tag mismatches unless explicitly allowed."""
    if not ref or not ref.strip():
        raise ProvenanceError("ref must not be empty")

    if allow_non_release_ref:
        return

    if not RELEASE_REF_PATTERN.match(ref):
        raise ProvenanceError(
            f"ref {ref!r} is not a protected release tag (expected vMAJOR.MINOR.PATCH). "
            "Pass --allow-non-release-ref only for local testing/POC builds; it must "
            "never be used on a production publication path."
        )

    if ref[1:] != gav_version:
        raise ProvenanceError(
            f"GAV version {gav_version!r} does not match release tag {ref!r}. "
            "The artifact must declare the exact version that was tagged and built."
        )


def validate_build_id(build_id: str) -> str:
    build_id = (build_id or "").strip()
    if not build_id:
        raise ProvenanceError("build id must not be empty")
    return build_id


def build_provenance_record(
    *,
    artifact_path: str,
    gav: str,
    ref: str,
    build_id: str,
    repository: str,
    artifact_type: str,
    repo_root: str,
    allow_non_release_ref: bool,
) -> dict:
    """Compute and assemble the provenance record. Raises ProvenanceError on failure."""
    artifact_type = (artifact_type or "").strip()
    if not artifact_type:
        raise ProvenanceError("artifact type must not be empty")

    repository = (repository or "").strip()
    if not repository:
        raise ProvenanceError("repository must not be empty")

    parsed_gav = split_gav(gav)
    validate_ref(ref, parsed_gav.version, allow_non_release_ref)
    validated_build_id = validate_build_id(build_id)

    sha256 = compute_sha256(artifact_path)
    commit = resolve_git_commit(repo_root)

    return {
        "schemaVersion": SCHEMA_VERSION,
        "artifactType": artifact_type,
        "gav": gav,
        "sha256": sha256,
        "source": {
            "repository": repository,
            "commit": commit,
            "ref": ref,
        },
        "build": {
            "id": validated_build_id,
        },
    }


def atomic_write_json(data: dict, output_path: str) -> None:
    """Write ``data`` as canonical, pretty-printed JSON atomically."""
    output_path = os.path.abspath(output_path)
    out_dir = os.path.dirname(output_path) or "."
    os.makedirs(out_dir, exist_ok=True)

    fd, tmp_path = tempfile.mkstemp(prefix=".generate-build-provenance-", dir=out_dir)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(data, handle, indent=2, sort_keys=True)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, output_path)
    except BaseException:
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        raise


def parse_args(argv: Optional[Sequence[str]]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a machine-readable build provenance record from the "
            "actual bytes of a just-built release artifact."
        ),
    )
    parser.add_argument(
        "--artifact-path",
        required=True,
        help="Path to the built artifact (e.g. the release jar) to hash.",
    )
    parser.add_argument(
        "--gav",
        required=True,
        help="Maven coordinate of the artifact as groupId:artifactId:version.",
    )
    parser.add_argument(
        "--ref",
        required=True,
        help="Git ref/tag that was built, e.g. v4.3.4.",
    )
    parser.add_argument(
        "--build-id",
        required=True,
        help="CI build identifier that produced the artifact.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to write the generated provenance JSON record to.",
    )
    parser.add_argument(
        "--repository",
        default=DEFAULT_REPOSITORY,
        help=f"Source repository in owner/name form (default: {DEFAULT_REPOSITORY}).",
    )
    parser.add_argument(
        "--artifact-type",
        default=DEFAULT_ARTIFACT_TYPE,
        help=f"Artifact type label (default: {DEFAULT_ARTIFACT_TYPE!r}).",
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Path to the git checkout to resolve the current commit from (default: cwd).",
    )
    parser.add_argument(
        "--allow-non-release-ref",
        action="store_true",
        help=(
            "POC/testing only: skip the protected release-tag check and the "
            "GAV-version/tag consistency check. Never use on a production "
            "publication path."
        ),
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)

    try:
        record = build_provenance_record(
            artifact_path=args.artifact_path,
            gav=args.gav,
            ref=args.ref,
            build_id=args.build_id,
            repository=args.repository,
            artifact_type=args.artifact_type,
            repo_root=args.repo_root,
            allow_non_release_ref=args.allow_non_release_ref,
        )
    except ProvenanceError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1

    if args.allow_non_release_ref:
        print(
            "[WARN] --allow-non-release-ref was set: release-tag protections are "
            "disabled. This record is NOT valid for production publication.",
            file=sys.stderr,
        )

    try:
        atomic_write_json(record, args.output)
    except OSError as exc:
        print(f"[ERROR] failed to write provenance record to {args.output!r}: {exc}", file=sys.stderr)
        return 1

    print(f"[INFO] wrote build provenance record to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
